#ifndef POINTCLOUD_RENDERER_COMMON_H
#define POINTCLOUD_RENDERER_COMMON_H

#define ZFAR 100.0f
#define ZNEAR 0.1f
#define MAX_STEPS 128
#define MIN_DIST 0.001f
#define BACKGROUND_COLOR make_float4(0,0,0,1)

#define SCREEN_WIDTH 1024.0
#define SCREEN_HEIGHT 768.0

#endif //POINTCLOUD_RENDERER_COMMON_H
